name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when there is a push to the main branch (change as needed)
  pull_request:
    branches:
      - main  # Optional: Deploy when a pull request is merged to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # You can specify your Node.js version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite app
      - name: Build Vite app
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
